---
title: "old_heatmap"
author: "Sam Rozal"
date: "2023-05-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#attach packages
library(tidyverse)
library(here)
library(janitor)
library(plotly)
library(lubridate)
library(kableExtra)
library(readxl)

gdrive_data <- "G:/My Drive"

```

```{r}
#read in the data 

slr_projections_old <- read_excel(here(gdrive_data, "/Sea_level_rise_projections.xlsx"))
slr_opc_sf <- read_excel(here(gdrive_data, "/sf_slr.xlsx"))
slr_projections_noaa <- read_excel(here(gdrive_data, "/slr_noaa_projections_transposed.xlsx"))
opc_guidance <- read_excel(here(gdrive_data, "/OPC_guidance.xlsx"))

```

```{r}
ggplot(data=slr_projections_old, aes(x=year, y=sea_level_rise_projection))+
  geom_point()+
   labs(x="Year", 
       y="Sea Level rise Projection (Feet)")+
  theme(plot.background = element_rect(fill="grey90")) +
  theme(panel.background = element_rect(fill="grey100"))+
  theme(legend.background= element_rect(fill= "grey100"))
```

```{r}
ggplot(data=slr_projections_old, aes(x=year, y=sea_level_rise_projection))+
  geom_density2d_filled()
```

```{r}
ggplot()+
  geom_bin2d(data=slr_projections_old, aes(x=year, y=sea_level_rise_projection, position= "identity"),binwidth = c(10 ,.5))+
  scale_fill_gradient(low="lightblue2", high = "navyblue")+
  geom_point(data=slr_projections_noaa, aes(x=Year, y=SLR_projection, color=Scenario))+
  geom_smooth(data=slr_projections_noaa, aes(x=Year, y=SLR_projection, color=Scenario))+
  geom_point(data=opc_guidance, aes(x=Year, y=State_Agency_Sea_Level_Rise_Action_Plan_Guidance), size=3)+
  labs(x="Year", 
       y="Sea Level rise Projection (Feet)")+
  theme(plot.background = element_rect(fill="grey90")) +
  theme(panel.background = element_rect(fill="grey100"))+
  theme(legend.background= element_rect(fill= "grey100"))+
  annotate("text", x= 2032, y=3, label=" State Agency 
  Sea Level Rise Action 
  Plan Guidance for 2050", size=3)+
  annotate("text", x= 2116, y=6, label="State Agency 
  Sea Level Rise Action 
  Plan Guidance for 2100", size=3)
  
```

```{r}
year_slr_proj <- slr_projections_old %>% 
  group_by(year) %>%
  summarize(mean_slr = mean(sea_level_rise_projection))

year_slr_proj
  
```
```{r}
kable(year_slr_proj, col.names = c("Year", "Mean SLR Projection (m)", caption = "Table. 1 Mean Sea Level rise Projections by Year")) %>% 
  kable_styling()

```

```{r}
ggplot()+
  geom_bin2d(data=slr_projections_old, aes(x=year, y=sea_level_rise_projection),binwidth = c(10 ,.5))
```

```{r}
ggplot()+
  geom_hex(data=slr_projections_old, aes(x=year, y=sea_level_rise_projection, position= "identity"),binwidth = c(10 ,1))+
  scale_fill_gradient(low="lightblue2", high = "navyblue")+
  geom_point(data=slr_projections_noaa, aes(x=Year, y=SLR_projection, color=Scenario))+
  geom_smooth(data=slr_projections_noaa, aes(x=Year, y=SLR_projection, color=Scenario))+
  geom_point(data=opc_guidance, aes(x=Year, y=State_Agency_Sea_Level_Rise_Action_Plan_Guidance), size=3)+
  labs(x="Year", 
       y="Sea Level Rise Projection (Feet)")+
  theme(plot.background = element_rect(fill="grey90")) +
  theme(panel.background = element_rect(fill="grey100"))+
  theme(legend.background= element_rect(fill= "grey100"))+
  ylim(0,12)+
  scale_x_continuous(breaks= seq(from = 2030, to= 2150,by=10))+
  scale_y_continuous(breaks= seq(from = 0, to= 12,by=1))
  
 
```
```{r}
ggplot()+
  geom_bin2d(data=slr_projections_old, aes(x=year, y=sea_level_rise_projection, position= "identity"),binwidth = c(10 ,.5))+
  scale_fill_gradient(low="lightblue2", high = "navyblue")+
  geom_point(data=slr_projections_noaa, aes(x=Year, y=SLR_projection, color=Scenario))+
  geom_smooth(data=slr_projections_noaa, aes(x=Year, y=SLR_projection, color=Scenario))+
  geom_point(data=opc_guidance, aes(x=Year, y=State_Agency_Sea_Level_Rise_Action_Plan_Guidance), size=3)+
  labs(x="Year", 
       y="Sea Level Rise Projection (Feet)")+
  theme(plot.background = element_rect(fill="grey90")) +
  theme(panel.background = element_rect(fill="grey100"))+
  theme(legend.background= element_rect(fill= "grey100"))+
  ylim(0,12)+
  scale_x_continuous(breaks= seq(from = 2030, to= 2150,by=10))+
  scale_y_continuous(breaks= seq(from = 0, to= 12,by=1))
  
  
```
